### ISSUE TITLE
NagBar Appears Blank after Safari 14 Update

### ISSUE THREAD

**Issue by timkite** [volendavidov/NagBar#12]
Does NagBar use any Safari components to do its thing? After the Safari 14 update on Catalina 10.15.6 it now appears blank on the menu bar, and left-clicking has no effect. The right-click menu and preferences dialog still work normally.
<img width="538" alt="image" src="https://user-images.githubusercontent.com/6933976/93481210-4f8ed900-f8cc-11ea-9aab-8ffb23c06e11.png">
The big empty space on the left between Bartender 3 and Toggl Track in the above image is NagBar as of this morning. Restarting the app or macOS has no impact. I can send console logs on request.

**Comment by timkite** [comment]
Well...interesting. One day later, no observable updates to anything and it's working normally again. Never mind, and sorry to bother you.

**Comment by volendavidov** [comment]
I tested with 10.15.7 and Safari 14 and there were no problems. It's a strange problem anyway and it's unlikely that it was related to Safari as the app doesn't use Safari components.
