### ISSUE TITLE
NagBar Doesn't Detect Correct Text Color in BigSur

### ISSUE THREAD

**Issue by timkite** [volendavidov/NagBar#13]
As of BigSur (macOS 11.0.1), the menu bar background and text color are based on wallpaper color instead of dark/light mode in the OS. As a result, NagBar will frequently get the text color choice wrong and display dark text on a dark menu bar or light text on a light menu bar. See screenshot for an example. In the screenshot, light mode is active, but the background is dark. Several 3rd party apps (to the right of NagBar, which is marked with a red circle) have already updated to correctly pick the correct text/icon color, so I'm guessing/hoping NagBar just needs tweaked to correctly detect the color it should be using?
![Screen Shot 2020-11-17 at 17 23 04](https://user-images.githubusercontent.com/6933976/99458125-05d96380-28fa-11eb-92d8-94ad0f92275a.png)

**Comment by nicoh88** [comment]
Same here! 

@volendavidov Can you fix this?

**Comment by volendavidov** [comment]
I will make a new release in a few days along with a fix for the table which shows up on status bar click - at the moment the text in the rows lays at the bottom and there is padding at the left and right edges.

**Comment by volendavidov** [comment]
Created a new release [1.3.7](https://github.com/volendavidov/NagBar/releases/tag/1.3.7)
