### ISSUE TITLE
M1 Native Build

### ISSUE THREAD

**Issue by timkite** [volendavidov/NagBar#15]
Will there be an arm64 native build of NagBar? Trying to build one myself results in linking errors with the Realm pod, which only seems to be able to build x86_64 binaries.

> ld: warning: ignoring file /Users/kite/Developer/NagBar/Pods/Realm/core/librealmcore-macosx.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "realm::BpTreeBase::replace_root(std::__1::unique_ptr<realm::Array, std::__1::default_delete<realm::Array> >)"...

Applying recommendations from Xcode as far as architecture settings and setting the `$(inherited)` build flag as recommended by CocoaPods doesn't make a difference. It does at least run (and build) fine under Rosetta2.

Platform: MacBook Air (M1, 2020)
OS: macOS 12.1 (21C52)
Xcode: Version 13.2.1 (13C100)
CocoaPods: 1.11.2
Ruby: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]
RubyGems: 3.2.32

**Comment by volendavidov** [comment]
I compiled a universal binary in https://github.com/volendavidov/NagBar/releases/download/1.3.7/NagBar-universal.zip.

The only change I've done is upgrading Realm from 3 to 10 without doing changes to the code itself. I tested and it works without issues, but I will be glad if you can share some feedback.

**Comment by timkite** [comment]
Working perfectly so far!

**Comment by joeMJ** [comment]
Hi Volen,

reported as being ARM64, running as like before.
TY!
John
