### ISSUE TITLE
feature request: show acknowledgements in the overview

### ISSUE THREAD

**Issue by unilynx** [volendavidov/NagBar#6]
The overview of services shows WARNING, CRITICAL etc, but does not show when someone has acknowledged an alarm

From what I understand from Linux users, Nagstamon uses something like a checkmark (√) to show when an alert is acknowleged. That would be nice for Nagbar too

**Comment by volendavidov** [comment]
In release [1.3.6](https://github.com/volendavidov/NagBar/releases/tag/1.3.6)
