### ISSUE TITLE
Not showing any alarms with Icinga Web 2.5.3

### ISSUE THREAD

**Issue by martensson** [volendavidov/NagBar#7]
Hi!

I am trying to replace Nagstamon with Nagbar which looks to be a better MacOS alternative.
I have added the server and it shows stutus "OK". But its not showing anything afterwards, just "No Alarms". Are there any logs or ways to debug the app?

Running IcingaWeb 2.5.3.

**Comment by volendavidov** [comment]
For Icinga2, you have to use the API, not IcingaWeb. So, the URL would be something like https://icinga2instance.com:5665/v1.
The "OK" status just indicates that the connection is successful (correct credentials, certificate and etc.) but does not indicate if the URL that is specified actually contains the monitoring information.

**Comment by martensson** [comment]
Thanks a lot @volendavidov, that did indeed solve the problem. Nagstamon uses the IcingaWeb, so I assumed NagBar did the same without actually trying the api. But maybe it would be nice to have a short notice somewhere to help others. Thanks!
