### ISSUE TITLE
Latest version filter bug

### ISSUE THREAD

**Issue by blundey** [volendavidov/NagBar#8]
If I set a filter as follows:

Host .*
Service Updates

Tick all boxes. 

It filters correctly, however it also filters hosts in downtime that are not related.

Regardless of what filter i put, it always hides hosts in downtime?

**Comment by volendavidov** [comment]
Thanks for reporting the bug. I will fix it in the coming days.

**Comment by volendavidov** [comment]
Fixed in release [1.3.6](https://github.com/volendavidov/NagBar/releases/tag/1.3.6)

**Comment by blundey** [comment]
Thanks!
